// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetFinderApi.Data;

namespace PetFinderApi.Migrations
{
    [DbContext(typeof(FinderContext))]
    [Migration("20201223054149_secondMIgration")]
    partial class secondMIgration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PetFinderApi.Models.Entity", b =>
                {
                    b.Property<long>("idEntity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReportCase")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Whatsapp")
                        .HasColumnType("bit");

                    b.HasKey("idEntity");

                    b.HasIndex("ReportCase");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("PetFinderApi.Models.Pet", b =>
                {
                    b.Property<long>("idPet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("NamePet")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .HasColumnType("varchar(80)");

                    b.Property<long?>("ReportCase")
                        .HasColumnType("bigint");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specie")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("idPet");

                    b.HasIndex("ReportCase");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetFinderApi.Models.Report", b =>
                {
                    b.Property<long>("Case")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("PetLost")
                        .HasColumnType("bigint");

                    b.Property<long>("ReportedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RescueDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("idEntity")
                        .HasColumnType("bigint");

                    b.Property<long?>("idPet")
                        .HasColumnType("bigint");

                    b.HasKey("Case");

                    b.HasIndex("idEntity");

                    b.HasIndex("idPet");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("PetFinderApi.Models.Entity", b =>
                {
                    b.HasOne("PetFinderApi.Models.Report", null)
                        .WithMany("entities")
                        .HasForeignKey("ReportCase");
                });

            modelBuilder.Entity("PetFinderApi.Models.Pet", b =>
                {
                    b.HasOne("PetFinderApi.Models.Report", null)
                        .WithMany("pets")
                        .HasForeignKey("ReportCase");
                });

            modelBuilder.Entity("PetFinderApi.Models.Report", b =>
                {
                    b.HasOne("PetFinderApi.Models.Entity", "entity")
                        .WithMany()
                        .HasForeignKey("idEntity");

                    b.HasOne("PetFinderApi.Models.Pet", "pet")
                        .WithMany()
                        .HasForeignKey("idPet");

                    b.Navigation("entity");

                    b.Navigation("pet");
                });

            modelBuilder.Entity("PetFinderApi.Models.Report", b =>
                {
                    b.Navigation("entities");

                    b.Navigation("pets");
                });
#pragma warning restore 612, 618
        }
    }
}
